const FEED='https://nsmevyhcpqijreuwbqkv.supabase.co/functions/v1/markets-feed';
const page=document.body.dataset.page;
let DATA=null;
let historyFilter='all';

const fmt=(v,a)=>{const n=Number(v);if(!Number.isFinite(n))return'-';if(a==='XAUUSD')return n.toFixed(2);if(String(a).endsWith('JPY'))return n.toFixed(3);return n.toFixed(5)};
const wat=v=>v?new Intl.DateTimeFormat('en-NG',{timeZone:'Africa/Lagos',day:'numeric',month:'short',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(v))+' WAT':'-';
const dateKey=v=>{if(!v)return'unknown';const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(v));const o={};parts.forEach(p=>o[p.type]=p.value);return `${o.year}-${o.month}-${o.day}`};
const isActive=s=>['WAITING','ACTIVE','TP1_HIT','TP2_HIT'].includes(String(s?.status||''));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

function row(s,expanded=false){
  const details=expanded?`<div class="signal-details"><div><span>ENTRY</span><b>${fmt(s.entryLow,s.asset)} - ${fmt(s.entryHigh,s.asset)}</b></div><div><span>SL</span><b>${fmt(s.sl,s.asset)}</b></div><div><span>TP1</span><b>${fmt(s.tp1,s.asset)}</b></div><div><span>TP2</span><b>${fmt(s.tp2,s.asset)}</b></div><div><span>TP3</span><b>${fmt(s.tp3,s.asset)}</b></div></div>`:'';
  return `<div class="row"><div><b>${esc(s.asset)}</b><small>${esc(wat(s.createdAt))}</small></div><div><strong class="${s.direction==='BUY'?'buy':'sell'}">${esc(s.direction)} - ${esc(s.pattern)}</strong><small>${esc(s.primaryTimeframe)} - ${esc(s.status)} - ${esc(s.grade||'')}</small>${details}</div><div class="right"><b>${Number(s.quality||0)}/20</b><small>quality</small></div></div>`;
}

function renderHero(s){
  const e=document.getElementById('hero');if(!e)return;
  if(!s){e.innerHTML='<div class="ey">CURRENT CORE SIGNAL</div><div class="empty">No active setup — V6 is scanning configured markets.</div>';return}
  const pr=s.portfolioRisk||{};
  e.innerHTML=`<div class="ey">CURRENT CORE SIGNAL</div><div class="hero"><div><h1>${esc(s.asset)}</h1><small>${esc(s.status)} - ${esc(s.grade)} - ${esc(wat(s.createdAt))}</small></div><strong class="${s.direction==='BUY'?'buy':'sell'}">${esc(s.direction)}</strong></div><p>${esc(s.pattern)} - ${esc(s.primaryTimeframe)} - Quality ${Number(s.quality||0)}/20</p><div class="levels"><div><span>ENTRY ZONE</span><b>${fmt(s.entryLow,s.asset)} - ${fmt(s.entryHigh,s.asset)}</b></div><div><span>STOP LOSS</span><b>${fmt(s.sl,s.asset)}</b></div><div><span>TP1</span><b>${fmt(s.tp1,s.asset)}</b></div><div><span>TP2</span><b>${fmt(s.tp2,s.asset)}</b></div><div><span>TP3</span><b>${fmt(s.tp3,s.asset)}</b></div></div><p>Portfolio: <b>${esc(pr.correlationLevel||'-')}</b> correlation · ${esc(pr.priority||'-')}${pr.recommendedMaxRiskPct==null?'':' · max risk '+Number(pr.recommendedMaxRiskPct).toFixed(2)+'%'}</p>`;
}

function renderMacro(d){const e=document.getElementById('macro');if(!e)return;const m=d.macro||{},n=d.nextMacroEvent;const cls=m.state==='VERIFIED'?'healthy':m.state==='STALE'||m.state==='UNAVAILABLE'?'danger':'warning';e.innerHTML=`<div class="${cls}"><b>${esc(m.state||'-')}</b></div><div class="small">Source: ${esc(m.source||'-')}<br>Updated: ${esc(wat(m.fetchedAt))}<br>Age: ${m.ageMin==null?'-':Number(m.ageMin).toFixed(1)+' min'} / ${Number(m.maxAgeMin||0)} min<br>${Number(m.eventCount||0)} events · ${Number(m.highImpactCount||0)} high impact</div>${n?`<div class="small" style="margin-top:8px"><b>Next:</b> ${esc(n.country)} · ${esc(n.title)}<br>${Number(n.minutesAway||0)} min · ${esc(wat(n.date))}</div>`:''}`}

function renderRisk(d){const e=document.getElementById('risk');if(!e)return;const r=d.riskPolicy||{},open=r.openExposures||[];e.innerHTML=`<div class="small">Base risk / trade: <b>${Number(r.riskPerTradePct||0).toFixed(2)}%</b><br>Correlated cap: <b>${Number(r.maxCorrelatedRiskPct||0).toFixed(2)}%</b><br>Total open cap: <b>${Number(r.maxTotalOpenRiskPct||0).toFixed(2)}%</b><br>Open signals: <b>${open.length}</b></div>`}

function renderHistory(){const e=document.getElementById('history');if(!e||!DATA)return;let rows=[...(DATA.recent||[])];if(historyFilter==='buy')rows=rows.filter(s=>s.direction==='BUY');if(historyFilter==='sell')rows=rows.filter(s=>s.direction==='SELL');if(historyFilter==='active')rows=rows.filter(isActive);if(historyFilter==='closed')rows=rows.filter(s=>!isActive(s));e.innerHTML=rows.length?rows.map(s=>row(s,true)).join(''):'<div class="card empty">No signals match this filter.</div>'}

function renderCalendar(){const rows=DATA?.recent||[],groups={};for(const s of rows){const d=dateKey(s.createdAt);(groups[d]??=[]).push(s)}const days=Object.keys(groups).sort().reverse(),cal=document.getElementById('calendar'),list=document.getElementById('calendarList');if(!cal||!list)return;if(!days.length){cal.innerHTML='<div class="empty">No dated signals yet.</div>';list.innerHTML='';return}cal.innerHTML=days.slice(0,28).map((d,i)=>`<button class="day ${i===0?'selected':''}" data-date="${esc(d)}"><b>${esc(d.slice(8))}</b><small>${groups[d].length} signal${groups[d].length===1?'':'s'}</small></button>`).join('');const show=d=>{list.innerHTML=`<div class="head"><h2>${esc(d)}</h2></div>`+groups[d].map(s=>row(s,true)).join('');cal.querySelectorAll('.day').forEach(b=>b.classList.toggle('selected',b.dataset.date===d))};cal.querySelectorAll('.day').forEach(b=>b.addEventListener('click',()=>show(b.dataset.date)));show(days[0])}

function renderSettings(d){const set=(id,v)=>{const e=document.getElementById(id);if(!e)return;e.textContent=v?'ON':'OFF';e.className=v?'on':'off'};set('tg',d.delivery?.telegram);set('email',d.delivery?.email);set('push',d.delivery?.push);const sys=document.getElementById('system');if(sys)sys.innerHTML=`Session: <b>${esc(d.sessionLabel||'-')}</b><br>Market status: <b>${esc(String(d.marketStatus||'-').replaceAll('_',' '))}</b><br>Engine: <b>${d.engineEnabled===false?'PAUSED':'ON'}</b><br>Macro: <b>${esc(d.macro?.state||'-')}</b><br>Learning: <b>${esc(d.learning?.mode||'-')}</b> · ${Number(d.learning?.terminalCount||0)}/${Number(d.learning?.minSample||30)} terminal samples`;const r=d.riskPolicy||{},risk=document.getElementById('settingsRisk');if(risk)risk.innerHTML=`Risk / trade: <b>${Number(r.riskPerTradePct||0).toFixed(2)}%</b><br>Correlated cap: <b>${Number(r.maxCorrelatedRiskPct||0).toFixed(2)}%</b><br>Total open cap: <b>${Number(r.maxTotalOpenRiskPct||0).toFixed(2)}%</b><br>Correlation soft limit: <b>${Number(r.correlationSoftLimit||0)}</b>`}

function setBadges(d){const live=document.getElementById('liveBadge'),session=document.getElementById('sessionBadge'),market=document.getElementById('marketBadge');if(live){live.textContent='LIVE · '+wat(d.updatedAt);live.classList.add('healthy')}if(session)session.textContent=d.sessionLabel||'SESSION —';if(market)market.textContent=String(d.marketStatus||'STATUS —').replaceAll('_',' ')}

async function load(){const status=document.getElementById('status'),refresh=document.getElementById('refresh');if(refresh){refresh.disabled=true;refresh.textContent='Refreshing…'}try{const r=await fetch(FEED+'?t='+Date.now(),{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Feed unavailable');DATA=d;setBadges(d);if(page==='markets'){renderHero(d.active);renderMacro(d);renderRisk(d);const e=document.getElementById('recent');if(e)e.innerHTML=(d.recent||[]).length?(d.recent||[]).map(s=>row(s,false)).join(''):'<div class="card empty">No verified signals found.</div>'}if(page==='history')renderHistory();if(page==='calendar')renderCalendar();if(page==='settings')renderSettings(d);if(status)status.textContent='Live V6 data updated '+wat(d.updatedAt)}catch(e){if(status)status.textContent='Connection issue: '+(e.message||e);const live=document.getElementById('liveBadge');if(live){live.textContent='CONNECTION ISSUE';live.classList.add('danger')}}finally{if(refresh){refresh.disabled=false;refresh.textContent='Refresh'}}}

document.getElementById('refresh')?.addEventListener('click',load);
document.querySelectorAll('#historyFilters .filter').forEach(btn=>btn.addEventListener('click',()=>{historyFilter=btn.dataset.filter||'all';document.querySelectorAll('#historyFilters .filter').forEach(b=>b.classList.toggle('active',b===btn));renderHistory()}));
load();setInterval(load,30000);
