const FEED='https://nsmevyhcpqijreuwbqkv.supabase.co/functions/v1/market-gold-validation-feed';
let DATA=null,filter='all';
const pct=v=>Number.isFinite(Number(v))?(Number(v)*100).toFixed(0)+'%':'-';
const n=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'-';
const wat=v=>v?new Intl.DateTimeFormat('en-NG',{timeZone:'Africa/Lagos',day:'2-digit',month:'short',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date(v))+' WAT':'-';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function metric(label,value,sub,cls=''){return `<div class="metric"><span>${esc(label)}</span><b class="${cls}">${esc(value)}</b><small>${esc(sub)}</small></div>`}
function renderMetrics(d){const s=d.summary||{},m=document.getElementById('metrics');m.innerHTML=[metric('TERMINAL GOLD V6',String(s.terminal||0),'completed entered samples'),metric('TP1 / NON-LOSS',pct(s.tp1OrBetterRate),'TP1 secured, BE or better','pos'),metric('SL BEFORE TP1',pct(s.slBeforeTp1Rate),'loss before first target',Number(s.slBeforeTp1Rate)>.45?'neg':''),metric('AVERAGE R-FLOOR',s.avgRFloor==null?'-':n(s.avgRFloor,2)+'R','conservative realized floor',Number(s.avgRFloor)>0?'pos':Number(s.avgRFloor)<0?'neg':'neutral')].join('')}
function renderUpgrade(d){const s=d.summary||{},e=document.getElementById('upgradeStatus'),lead=s.avgPreAlertLeadMin==null?'Collecting':n(s.avgPreAlertLeadMin,1)+' min';e.innerHTML=`<div><div class="ey">XAU-EXEC-2 SAMPLE</div><b>${Number(s.postUpgradeSetups||0)} setups</b><small>${Number(s.postUpgradeTerminal||0)} terminal results</small></div><div><div class="ey">PRE-ALERT LEAD</div><b>${esc(lead)}</b><small>target: about 10 minutes or earlier when confirmation is building</small></div><div><div class="ey">RULE STATUS</div><b>${d.framework?.frozen?'FROZEN ✅':'REVIEW'}</b><small>No automatic threshold changes during evidence collection.</small></div>`}
function renderPatterns(d){const e=document.getElementById('patterns'),rows=d.patternPerformance||[];if(!rows.length){e.innerHTML='<div class="empty">No completed Gold pattern samples yet.</div>';return}e.innerHTML=rows.slice(0,10).map(x=>`<div class="pattern-item"><div class="pattern-head"><div><b>${esc(x.pattern)}</b><small>${x.n} sample${x.n===1?'':'s'} · Avg ${n(x.avgR,2)}R</small></div><strong class="${x.avgR>0?'pos':x.avgR<0?'neg':'neutral'}">${pct(x.tp1Rate)}</strong></div><div class="bar"><i style="width:${Math.max(0,Math.min(100,x.tp1Rate*100))}%"></i></div><small>TP1/non-loss rate · SL ${pct(x.slRate)}</small></div>`).join('')}
function row(x){const rcls=x.rFloor>0?'pos':x.rFloor<0?'neg':'neutral',tags=[x.ruleVersion,x.proLibrary?'PRO-LIB-1':null,x.confirmation?'M15 CONFIRMED':null,x.retest&&x.retest!=='-'?'RETEST '+x.retest:null].filter(Boolean);return `<article class="validation-row"><div class="topline"><div><div class="ey">${wat(x.createdAt)}</div><h3>${esc(x.direction)} · ${esc(x.corePattern)}</h3></div><strong class="${rcls}">${esc(x.outcome)}${x.rFloor==null?'':' · '+n(x.rFloor,1)+'R'}</strong></div><div>${tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="validation-grid"><div><span>PRO BEST</span><b>${esc(x.professionalBest)}</b></div><div><span>PRO SCORE</span><b>${n(x.professionalScore,0)}/100</b></div><div><span>HTF MAP</span><b>${esc(x.htf)}</b></div><div><span>REJECTION</span><b>${esc(x.rejection)}</b></div><div><span>ENTRY</span><b class="mono">${n(x.entryLow)} - ${n(x.entryHigh)}</b></div><div><span>PRE-ALERT LEAD</span><b>${x.preAlertLeadMin==null?'-':n(x.preAlertLeadMin,1)+' min'}</b></div><div><span>FINAL → ACTIVE</span><b>${x.finalToActiveMin==null?'-':n(x.finalToActiveMin,1)+' min'}</b></div><div><span>QUALITY</span><b>${n(x.quality,0)}/20</b></div></div></article>`}
function renderRecent(){const e=document.getElementById('recentValidation');let rows=DATA?.recent||[];if(filter==='post')rows=rows.filter(x=>x.ruleVersion==='XAU-EXEC-2');if(filter==='entered')rows=rows.filter(x=>x.rFloor!==null);if(filter==='rejected')rows=rows.filter(x=>String(x.outcome)==='Rejected');e.innerHTML=rows.length?rows.map(row).join(''):'<div class="card empty">No setups match this filter yet.</div>'}
function renderHealth(d){const h=d.health||{},b=document.getElementById('healthBadge');b.textContent=(h.last_overall||'UNKNOWN')+' · '+(h.last_mode||'');b.className='status-pill '+(['HEALTHY','MONITORING'].includes(h.last_overall)?'healthy':h.last_overall==='ATTENTION'?'warning':'danger')}
async function load(){const st=document.getElementById('status'),btn=document.getElementById('refresh');if(btn){btn.disabled=true;btn.textContent='Refreshing…'}try{const r=await fetch(FEED+'?t='+Date.now(),{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Feed unavailable');DATA=d;renderHealth(d);renderMetrics(d);renderUpgrade(d);renderPatterns(d);renderRecent();st.textContent='Gold validation updated '+wat(d.updatedAt)}catch(e){st.textContent='Connection issue: '+(e.message||e);document.getElementById('healthBadge').textContent='CONNECTION ISSUE'}finally{if(btn){btn.disabled=false;btn.textContent='Refresh'}}}
document.getElementById('refresh')?.addEventListener('click',load);
document.querySelectorAll('#validationFilters .filter').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter||'all';document.querySelectorAll('#validationFilters .filter').forEach(x=>x.classList.toggle('active',x===b));renderRecent()}));
load();setInterval(load,60000);
